### ISSUE TITLE
Please push a release

### ISSUE THREAD

**Issue by jkohen** [census-ecosystem/kubernetes-operator#17]
The README file encourages running `deploy/deploy.sh`, but the image that is picked up by default doesn't work. The reason is that it was built with an unreleased copy of the OpenCensus `resourcekeys` package that used different label names, so the OpenCensus library doesn't recognize any of the labels exported by this operator. I confirmed that rebuilding at `HEAD` produces the expected labels.

I spent a couple hours debugging this :-(

@rghetia can you help?

**Comment by rghetia** [comment]
@jkohen I'll fix it today.

**Comment by rghetia** [comment]
released gcr.io/opencensus/operator:0.2.0
